export enum SPLIT_TYPE {
  EQUAL = "EQUAL",
  PERCENTAGE = "PERCENTAGE",
  SHARE = "SHARE",
}

export enum SHARE_TYPE {
  NONE = "NONE",
  GROUP = "GROUP",
  FRIENDS = "FRIENDS",
}

export enum TIME_PERIOD {
  WEEKLY = "WEEKLY",
  BIWEEKLY = "BIWEEKLY",
  MONTHLY = "MONTHLY",
  QUATERLY = "QUATERLY",
  HALF_YEARLY = "HALF_YEARLY",
  YEARLY = "YEARLY",
}

export enum FRIEND_STATUS {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  BLOCKED = "BLOCKED",
}

export enum RECURRENCE_TYPE {
  DEBIT = "DEBIT",
  CREDIT = "CREDIT",
}

export enum TXN_CATEGORY {
  RENT = "RENT",
  BILLS = "BILLS",
  UTILITIES = "UTILITIES",
  GROCERIES = "GROCERIES",
  ORDERING_IN = "ORDERING_IN",
  DINING_OUT = "DINING_OUT",
  ENTERTAINMENT = "ENTERTAINMENT",
  TRANSPORTATION = "TRANSPORTATION",
  CAR = "CAR",
  SHOPPING = "SHOPPING",
  TRAVEL = "TRAVEL",
  INVESTMENT = "INVESTMENT",
  COSMETIC = "COSMETIC",
  PETS = "PETS",
  SUBSCRIPTIONS = "SUBSCRIPTIONS",
  HEALTHCARE = "HEALTHCARE",
  GYM = "GYM",
  INCOME = "INCOME",
  SAVING = "SAVING",
  GENERAL = "GENERAL",
  BOOZE = "BOOZE",
}

export enum TXN_TYPE {
  INCOME = "INCOME",
  EXPENSE = "EXPENSE",
  INVESTMENT = "INVESTMENT",
  LOAN_GIVEN = "LOAN_GIVEN",
  LOAN_TAKEN = "LOAN_TAKEN",
}
