// export enum SPLIT_TYPE {
//   EQUAL = "EQUAL",
//   PERCENTAGE = "PERCENTAGE",
//   SHARE = "SHARE",
// }
//
// export enum SHARE_TYPE {
//   NONE = "NONE",
//   GROUP = "GROUP",
//   FRIENDS = "FRIENDS",
// }
//
// export enum BUDGET_PERIOD {
//   WEEKLY = "WEEKLY",
//   BIWEEKLY = "BIWEEKLY",
//   MONTHLY = "MONTHLY",
//   QUATERLY = "QUATERLY",
//   HALF_YEARLY = "HALF_YEARLY",
//   YEARLY = "YEARLY",
// }
//
// export enum RECURRENCE_PERIOD {
//   WEEKLY = "WEEKLY",
//   BIWEEKLY = "BIWEEKLY",
//   MONTHLY = "MONTHLY",
//   QUATERLY = "QUATERLY",
//   HALF_YEARLY = "HALF_YEARLY",
//   YEARLY = "YEARLY",
// }

import { ACCOUNT_TYPE } from "@/db";

export const initialAccountSeed: Map<string, ACCOUNT_TYPE> = new Map([
  ["MAIN", ACCOUNT_TYPE.INCOME],
  ["EXTERNAL", ACCOUNT_TYPE.EXTERNAL],
  ["LOAN_GIVEN", ACCOUNT_TYPE.LOAN_GIVEN],
  ["LOAN_TAKES", ACCOUNT_TYPE.LOAN_TAKEN],
  ["RENT", ACCOUNT_TYPE.EXPENSE],
  ["BILLS", ACCOUNT_TYPE.EXPENSE],
  ["UTILITIES", ACCOUNT_TYPE.EXPENSE],
  ["GROCERIES", ACCOUNT_TYPE.EXPENSE],
  ["ORDERING_IN", ACCOUNT_TYPE.EXPENSE],
  ["DINING_OUT", ACCOUNT_TYPE.EXPENSE],
  ["ENTERTAINMENT", ACCOUNT_TYPE.EXPENSE],
  ["TRANSPORTATION", ACCOUNT_TYPE.EXPENSE],
  ["CAR", ACCOUNT_TYPE.EXPENSE],
  ["SHOPPING", ACCOUNT_TYPE.EXPENSE],
  ["TRAVEL", ACCOUNT_TYPE.EXPENSE],
  ["COSMETIC", ACCOUNT_TYPE.EXPENSE],
  ["PETS", ACCOUNT_TYPE.EXPENSE],
  ["SUBSCRIPTIONS", ACCOUNT_TYPE.EXPENSE],
  ["HEALTHCARE", ACCOUNT_TYPE.EXPENSE],
  ["GYM", ACCOUNT_TYPE.EXPENSE],
  ["GENERAL", ACCOUNT_TYPE.EXPENSE],
  ["BOOZE", ACCOUNT_TYPE.EXPENSE],
]);
